name: Update README with WakaTime Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Executa diariamente à meia-noite UTC
  workflow_dispatch:      # Permite execução manual

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # Permite editar o README
      pull-requests: write  # Opcional para PRs
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update README with WakaTime Stats
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}  # Nome correto da secret
          GH_TOKEN: ${{ secrets.GH_TOKEN }}                  # Nome correto da secret
          SHOW_TITLE: "false"            # Remove título padrão
          SHOW_EDITORS: "true"           # Mostra editores (ex: VS Code)
          SHOW_OS: "true"                # Mostra sistemas operacionais
          SHOW_CATEGORIES: "true"        # Mostra categorias
