name: Update README with WakaTime Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Executa diariamente à meia-noite UTC
  workflow_dispatch:      # Permite execução manual

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # Permite editar o README

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Waka - Readme
        uses: athul/waka-readme@v0.3.1
        with:
          # Configurações obrigatórias
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

          # Configurações básicas
          SHOW_TITLE: "false"            # Remove título padrão
          SHOW_EDITORS: "true"           # Mostra editores (VS Code)
          SHOW_OS: "true"                # Mostra sistemas operacionais
          SHOW_CATEGORIES: "true"        # Mostra categorias
          
          # Configurações recomendadas
          TIME_RANGE: all_time           # Mostra dados acumulados
          LANG_COUNT: 6                  # Top 5 linguagens (mude para 10 se preferir)
          SHOW_TIME: "true"              # Mostra tempo total
          SECTION_NAME: "waka"           # Seção no README <!--START_SECTION:waka-->
          
          # Configurações opcionais
          TIME_RANGE: all_time          # Período dos dados ("last_7_days" ou "all_time")
          COMMIT_MESSAGE: "📊 Atualização automática das estatísticas WakaTime"
          CODE_LANG: rust
          BLOCKS: "▱▰"      # Blocos de progresso personalizados
          LOCALE: "br"
