name: Update README with WakaTime Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Executa diariamente à meia-noite UTC
  workflow_dispatch:      # Permite execução manual

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # Permite editar o README
      pull-requests: write  # Permite criar PRs (opcional)

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update README with WakaTime Stats
        uses: athul/waka-readme@master
        with:
          # Configurações obrigatórias
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

          # Configurações básicas
          SHOW_TITLE: "false"            # Remove título padrão
          SHOW_EDITORS: "true"           # Mostra editores (ex: VS Code)
          SHOW_OS: "true"                # Mostra sistemas operacionais
          SHOW_CATEGORIES: "true"        # Mostra categorias
          SHOW_LOCATION: "true"          # Mostra localização
          SHOW_EMAIL: "true"             # Mostra e-mail
          SHOW_WEBSITE: "true"           # Mostra website
          SHOW_JOINED_DATE: "true"       # Mostra data de cadastro

          # Configurações de exibição
          TIME_RANGE: all_time           # Período dos dados
          LANG_COUNT: 10                 # Número de linguagens
          SHOW_TIME: "true"              # Mostra tempo total
          SHOW_TOTAL: "true"             # Mostra contagem total
          SHOW_MASKED_TIME: "false"      # Oculta tempo mascarado
          STOP_AT_OTHER: "true"          # Para em "Other"
          SECTION_NAME: "waka"           # Seção no README
          LOCALE: "br"                   # Localização BR

          # Personalização avançada
          CODE_LANG: "rust"              # Estilo de código
          BLOCKS: "▱▰"                   # Blocos personalizados
          IGNORED_LANGUAGES: "YAML,JSON,TOML"  # Linguagens ignoradas
          COMMIT_MESSAGE: "📊 Atualização automática das estatísticas WakaTime"
          TARGET_BRANCH: "main"          # Branch alvo
          TARGET_PATH: "README.md"       # Arquivo alvo
- name: Update README
  uses: athul/waka-readme@master
  with:
    WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
    GH_TOKEN: ${{ secrets.GH_TOKEN }}
    SECTION_NAME: "waka"  # Deve bater com <!--START_SECTION:waka-->
    TARGET_PATH: "README.md"  # Especifica o arquivo exato
    PRESERVE_EXTRA_SECTIONS: true  # 🔥 Opção crucial que protege outras seções
