name: Update README with WakaTime Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Executa diariamente à meia-noite UTC
  workflow_dispatch:      # Permite execução manual

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # Permite editar o README
      pull-requests: write  # Permite criar PRs (opcional)

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update README with WakaTime Stats
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TITLE: "false"
          SHOW_EDITORS: "true"
          SHOW_OS: "true"
          SHOW_CATEGORIES: "true"
          SHOW_LOCATION: "true"
          SHOW_EMAIL: "true"
          SHOW_WEBSITE: "true"
          SHOW_JOINED_DATE: "true"
          TIME_RANGE: all_time
          LANG_COUNT: 10
          SHOW_TIME: "true"
          SHOW_TOTAL: "true"
          SHOW_MASKED_TIME: "false"
          STOP_AT_OTHER: "true"
          SECTION_NAME: "waka"
          LOCALE: "br"
          CODE_LANG: "rust"
          BLOCKS: "▱▰"
          IGNORED_LANGUAGES: "YAML,JSON,TOML"
          COMMIT_MESSAGE: "📊 Atualização automática das estatísticas WakaTime"
          TARGET_BRANCH: "main"
          TARGET_PATH: "README.md"
